# Generated by Django 5.2.15 on 2026-06-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organizationmember_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
